#!/bin/bash

# ------------------------------------------------------------------------------
# VARIABLES AND DEFAULTS
# ------------------------------------------------------------------------------

ACTION="${1}"

CURRENT_DIR="$(dirname $(realpath ${0}))"
DATA_DIR="${CURRENT_DIR}/data"
COMMANDS_DIR="${DATA_DIR}/comands"
SNIPPET_SECTIONS_DIR="${DATA_DIR}/snippets"

ALL_SECTIONS=( $(ls $SNIPPET_SECTIONS_DIR) )



# ------------------------------------------------------------------------------
# HELPER FUNCTIONS
# ------------------------------------------------------------------------------

echo_color () {
  local COLOR="${1}"
  local MESSAGE="${2}"

  local NO_COLOR='\033[0m'

  case "${COLOR}" in
    "red")
      COLOR='\033[0;31m'
      ;;
    "green")
      COLOR='\033[0;32m'
      ;;
    "yellow")
      COLOR='\033[0;33m'
      ;;
    "blue")
      COLOR='\033[0;34m'
      ;;
    "purple")
      COLOR='\033[0;35m'
      ;;
    "cyan")
      COLOR='\033[0;36m'
      ;;
    "grey")
      COLOR='\033[à;37m'
      ;;
    *)
      log "ERROR" "Unknown loc color '${COLOR}'."
  esac

  echo -e "${COLOR}${MESSAGE}${NO_COLOR}"
}

log () {
  local SEVERITY="${1}"
  local MESSAGE="${2}"

  echo_color "red" "[${SEVERITY}] ${MESSAGE}"
  echo

  if [[ "${SEVERITY}" == "ERROR" ]]; then
    show_help
    exit 1
  fi
}


# ------------------------------------------------------------------------------
# COMMANDS
# ------------------------------------------------------------------------------

show_help () {
  echo_color "cyan" "Commands:"
  cat << EOF
  cheat list all snippets
  cheat list sections
  cheat list <SECTION> snippets

  cheat show <SECTION> snippet
  cheat show <SECTION> snippet <SNIPPET_NAME>
  cheat show all [<SECTION>] snippets

  cheat grep <STRING>

  cheat <BINARY> [online]

EOF

  echo_color "cyan" "Cheat data location:"
  echo "  ${DATA_DIR}"
  echo
}

list_all_snippets () {
  echo "cheat list all snippets"

  # list all snippets in all sections
  # Output snippets in sections:
  # <SECTION>
  #   <SNIPPET_NAME>
  #   <SNIPPET_NAME>
}

list_sections () {
  echo "cheat list sections"

  echo_color "cyan" "The following sections exist:"
  for SECTION in "${ALL_SECTIONS[@]}"; do
    echo "  ${SECTION}"
  done
}

list_snippets_for_section () {
  local SECTION="${1}"

  echo "cheat list <SECTION> snippets"

  # List all snippets in said section
}

show_all_snippets () {
  echo "cheat show all snippets"

  # Display content of all snippets in all sections
}

show_all_snippets_for_section () {
  local SECTION="${1}"

  echo "cheat show all <SECTION> snippets"

  # Display content of all snippets in said section
}

show_snippet_for_section () {
  local SECTION="${1}"

  echo "cheat show <SECTION> snippet"

  # Select a snippet in a section that you want to see
  # echo "There are ${#array[@]} dirs in the current path"; select dir in "${array[@]}"; do echo "you selected ${dir}"'!'; break; done
}

show_snippet () {
  local SECTION="${1}"
  local SNIPPET_NAME="${2}"

  echo "cheat show <SECTION> snippet <SNIPPET_NAME>"

  # Display content of snippet name in section
}

grep_string () {
  local STRING="${1}"

  echo "cheat grep <STRING>"

  # Show results containg string
}

cheat_binary () {
  local BINARY="${1}"
  local ONLINE="${2}"

  echo "cheat <BINARY> [online]"

  # Display all in commands
  # If online is True, also use cheat.sh
}

# ------------------------------------------------------------------------------
# MAIN
# ------------------------------------------------------------------------------

case "${ACTION}" in
  "help"|"-h"|"--help")
    show_help
    ;;

  "list")
    TYPE="${2}"
    if [[ -z ${TYPE} ]]; then
      log "ERROR" "Action 'list' requires a second argument. Refer to the help message for more info."
    else
      case "${TYPE}" in
        "all")
          WHAT="${3}"
          if [[ "${WHAT}" == "snippets" ]]; then
            list_all_snippets
          else
            log "ERROR" "Action 'list all' requires a third argument. Refer to the help message for more info."
          fi
        ;;
        "sections")
          list_sections
        ;;
        *)
          SECTION="${TYPE}"
          WHAT="${3}"
          if [[ "${WHAT}" == "snippets" ]]; then
            list_snippets_for_section "${SECTION}"
          else
            log "ERROR" "Action 'list all' requires a third argument. Refer to the help message for more info."
          fi
      esac
    fi
    ;;

  "show")
    TYPE="${2}"
    if [[ -z ${3} ]]; then
      log "ERROR" "Action 'show' requires at least a second and third argument. Refer to the help message for more info."
    else
      case "${TYPE}" in
        "all")
          WHAT="${3}"
          if [[ "${WHAT}" == "snippets" ]]; then
            show_all_snippets
          else
            SECTION="${WHAT}"
            WHAT="${4}"
            if [[ -z ${WHAT} ]]; then
              log "ERROR" "Action 'show all <SECTION>' requires a fourth argument. Refer to the help message for more info."
            else
              show_all_snippets_for_section "${SECTION}"
            fi
          fi
        ;;
        *)
          SECTION="${TYPE}"
          WHAT="${3}"
          SNIPPET_NAME="${4}"
          if [[ -z ${SNIPPET_NAME} ]]; then
            if [[ -z ${WHAT} ]]; then
              log "ERROR" "Action 'show <SECTION>' requires a third and optionally fourth argument. Refer to the help message for more info."
            elif [[ "${WHAT}" != "snippet" ]]; then
              log "ERROR" "Unknown argument '${WHAT}' for action 'show <SECTION>. Refer to the help message for more info."
            else
              show_snippet_for_section "${SECTION}"
            fi
          else
            show_snippet "${SECTION}" "${SNIPPET_NAME}"
          fi
      esac
    fi
    ;;

  "grep")
      STRING="${2}"
      if [[ -z ${STRING} ]]; then
        log "ERROR" "Please provide a string to grep."
      fi
      grep_string "${STRING}"
    ;;

  *)
    BINARY="${ACTION}"
    ONLINE="${2}"
    if [[ -z ${ONLINE} ]]; then
      ONLINE="False"
    elif [[ "${ONLINE}" == "online" ]]; then
      ONLINE="True" 
    else
      log "ERROR" "Binary cheat has no option '${ONLINE}'. Only 'online' is a valid option or provide none."
    fi
    cheat_binary "${BINARY}" "${ONLINE}"
    ;;
esac

exit 0

