#!/bin/bash
set -e
set -u
set -o pipefail

# ------------------------------------------------------------------------------
# VARIABLES AND DEFAULTS
# ------------------------------------------------------------------------------

ACTION="${1:-}"

CURRENT_DIR="$(dirname $(realpath ${0}))"
BIN_DIR="${CURRENT_DIR}/bin"
DATA_DIR="${CURRENT_DIR}/data"
COMMANDS_DIR="${DATA_DIR}/commands"
SNIPPET_SECTIONS_DIR="${DATA_DIR}/snippets"
ALL_SECTIONS=( $(ls ${SNIPPET_SECTIONS_DIR}) )

# Colors
NO_COLOR='\033[0m'
RED='\033[0;31m'
RED_BOLD='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
PURPLE_BOLD='\033[1;35m'
CYAN='\033[0;36m'
CYAN_BOLD='\033[1;36m'
GREY='\033[0;90m'
GREY_BOLD='\033[1;90m'

#    cat "${SECTION_DIR}/${SNIPPET}" \
#      | sed "s/^# \(.*\)$/$(printf ${GREY_BOLD})#\1 $(printf ${NO_COLOR})/g" \
#      | sed "s/^##\(.*\)$/$(printf ${GREY})##\1 $(printf ${NO_COLOR})/g"


# ------------------------------------------------------------------------------
# HELPER FUNCTIONS
# ------------------------------------------------------------------------------

echo_color () {
  local COLOR="${1}"
  local MESSAGE="${2}"

  case "${COLOR}" in
    "red")
      COLOR="${RED}"
      ;;
    "red_bold")
      COLOR="${RED_BOLD}"
      ;;
    "green")
      COLOR="${GREEN}"
      ;;
    "yellow")
      COLOR="${YELLOW}"
      ;;
    "blue")
      COLOR="${BLUE}"
      ;;
    "purple")
      COLOR="${PURPLE}"
      ;;
    "purple_bold")
      COLOR="${PURPLE_BOLD}"
      ;;
    "cyan")
      COLOR="${CYAN}"
      ;;
    "cyan_bold")
      COLOR="${CYAN_BOLD}"
      ;;
    "grey")
      COLOR="${GREY}"
      ;;
    "grey_bold")
      COLOR="${GREY_BOLD}"
      ;;
    *)
      log "ERROR" "Unknown loc color '${COLOR}'."
  esac

  echo -e "${COLOR}${MESSAGE}${NO_COLOR}"
}

log () {
  local SEVERITY="${1}"
  local MESSAGE="${2}"

  echo_color "red" "[${SEVERITY}] ${MESSAGE}"
  echo

  if [[ "${SEVERITY}" == "ERROR" ]]; then
    show_help
    exit 1
  fi
}

set_bat_binary () {
  # Configure Bat: https://github.com/sharkdp/bat
  if [[ "${OSTYPE:-}" == "darwin"* ]]; then
    BAT="${BIN_DIR}/bat_apple_x86_darwin"
  else
    BAT="${BIN_DIR}/bat_linux_x86_gnu_musl"
  fi
}

print_file () {
  local FILE="${1}"
  local FILE_NAME="$(basename ${FILE})"
  local BAT=""

  set_bat_binary

  ${BAT} \
    --color always \
    --decorations always \
    --paging never \
    --style header,plain,grid \
    --file-name "$(echo ${FILE_NAME%.*} | sed 's/_/ /g')" \
    --language "${FILE_NAME##*.}" \
    "${FILE}"
}

print_command () {
  local LANGUAGE="${1}"
  local COMMAND="${2}"

  set_bat_binary
  
  echo "${COMMAND}" | ${BAT} \
    --color always \
    --decorations always \
    --paging never \
    --style plain \
    --language "${LANGUAGE}"
}


# ------------------------------------------------------------------------------
# COMMANDS
# ------------------------------------------------------------------------------

# cheat [help|-h|--help]
show_help () {
  echo_color "cyan_bold" "Commands:"
  cat << EOF
  cheat list all snippets
  cheat list sections
  cheat list <SECTION> snippets

  cheat show <SECTION> snippet
  cheat show <SECTION> snippet <SNIPPET_NAME>
  cheat show all [<SECTION>] snippets

  cheat grep <STRING>

  cheat <BINARY> [online]

EOF

  echo_color "cyan_bold" "Cheat data location:"
  echo "  ${DATA_DIR}"
  echo
}

# cheat list all snippets
list_all_snippets () {
  local local SECTION_DIR=""
  local ALL_SNIPPETS=()

  for SECTION in "${ALL_SECTIONS[@]}"; do
    SECTION_DIR="${SNIPPET_SECTIONS_DIR}/${SECTION}"
    ALL_SNIPPETS=( $(ls ${SECTION_DIR}) )

    echo_color "cyan_bold" "All snippets in section '${SECTION}':"
    for SNIPPET in "${ALL_SNIPPETS[@]}"; do
      echo "  - ${SNIPPET}"
    done
    echo
  done
}

# cheat list sections
list_sections () {
  echo_color "cyan_bold" "The following sections exist:"
  for SECTION in "${ALL_SECTIONS[@]}"; do
    echo "  - ${SECTION}"
  done
}

# cheat list <SECTION> snippets
list_snippets_for_section () {
  local SECTION="${1}"

  local SECTION_DIR="${SNIPPET_SECTIONS_DIR}/${SECTION}"
  if [[ ! -d "${SECTION_DIR}" ]]; then
    log "ERROR" "Section '${SECTION}' does not exist."
  fi

  echo_color "cyan" "The following snippets exist for section '${SECTION}':"
  local ALL_SNIPPETS=( $(ls ${SECTION_DIR}) )
  for SNIPPET in "${ALL_SNIPPETS[@]}"; do
    echo "  - ${SNIPPET}" | sed 's/_/ /g'
  done
}

# cheat show all snippets
show_all_snippets () {
  local SECTION_DIR=""
  local ALL_SNIPPETS=()

  for SECTION in "${ALL_SECTIONS[@]}"; do
    SECTION_DIR="${SNIPPET_SECTIONS_DIR}/${SECTION}"
    ALL_SNIPPETS=( $(ls ${SECTION_DIR}) )

    echo_color "cyan_bold" "All snippets in section '${SECTION}':"
    echo
    for SNIPPET in "${ALL_SNIPPETS[@]}"; do
      print_file "${SECTION_DIR}/${SNIPPET}"
    done
  done
}

# cheat show all <SECTION> snippets
show_all_snippets_for_section () {
  local SECTION="${1}"

  local SECTION_DIR="${SNIPPET_SECTIONS_DIR}/${SECTION}"
  if [[ ! -d "${SECTION_DIR}" ]]; then
    log "ERROR" "Section '${SECTION}' does not exist."
  fi

  echo_color "cyan_bold" "All snippets in section '${SECTION}':"
  echo
  local ALL_SNIPPETS=( $(ls ${SECTION_DIR}) )
  for SNIPPET in "${ALL_SNIPPETS[@]}"; do
    print_file "${SECTION_DIR}/${SNIPPET}"
  done
}

# cheat show <SECTION> snippet
show_snippet_for_section () {
  local SECTION="${1}"

  local SECTION_DIR="${SNIPPET_SECTIONS_DIR}/${SECTION}"
  if [[ ! -d "${SECTION_DIR}" ]]; then
    log "ERROR" "Section '${SECTION}' does not exist."
  fi

  local ALL_SNIPPETS=( $(ls ${SECTION_DIR}) )
  echo_color "cyan" "There are ${#ALL_SNIPPETS[@]} snippets in section '${SECTION}'."
  echo_color "cyan" "Please select the snippet that you want to view."
  select SNIPPET in "${ALL_SNIPPETS[@]}"; do
    print_file "${SECTION_DIR}/${SNIPPET}"
    break
  done
}

# cheat show <SECTION> snippet <SNIPPET_NAME>
show_snippet () {
  local SECTION="${1}"
  local SNIPPET_NAME="${2}"

  local SECTION_DIR="${SNIPPET_SECTIONS_DIR}/${SECTION}"
  if [[ ! -d "${SECTION_DIR}" ]]; then
    log "ERROR" "Section '${SECTION}' does not exist."
  fi

  local SNIPPET="${SECTION_DIR}/$(ls ${SECTION_DIR} | grep ${SNIPPET_NAME})"
  if [[ ! -f "${SNIPPET}" ]]; then
    log "ERROR" "Snippet '${SNIPPET_NAME}' in section '${SECTION}' does not exist."
  fi

  print_file "${SNIPPET}"
}

# cheat grep <STRING>
grep_string () {
  local GREP_ARGS_AND_STRING="${1}"
  local FILE=""
  local OLD_FILE=""
  local LANGUAGE=""
  local LINE_NR=""
  local DATA=""
  local SECTION=""
  local SNIPPET_NAME=""
  local FIRST_RESULT_SHOWN=False

  grep -rn ${GREP_ARGS_AND_STRING} "${DATA_DIR}" | while read -r RESULT; do
    FILE="$(echo ${RESULT} | cut -d ':' -f 1)"
    LANGUAGE="${FILE##*.}"
    LINE_NR="$(echo ${RESULT} | cut -d ':' -f 2)"
    DATA="$(echo ${RESULT} | cut -d ':' -f 3-)"

    # Remove common part from file name (data dir prefix)
    FILE_SHORT=${FILE#"$DATA_DIR/"}

    # If the previous file does not equal the current file, print a devider
    if [[ "${FILE}" != "${OLD_FILE}" ]]; then
      if [[ "${FIRST_RESULT_SHOWN}" == "False" ]]; then
        FIRST_RESULT_SHOWN=True
      else
        echo_color "red_bold" "---"
      fi
    fi
    OLD_FILE="${FILE}"

    # If it is a snippet, show the command how to view it
    TYPE="$(echo ${FILE_SHORT} | cut -d '/' -f 1)"
    if [[ "${TYPE}" == "snippets" ]]; then
      SECTION="$(echo ${FILE_SHORT} | cut -d '/' -f 2)"
      SNIPPET_NAME="$(echo ${FILE_SHORT} | cut -d '/' -f 3)"
      echo_color "yellow" "Command: cheat show ${SECTION} snippet ${SNIPPET_NAME%.*}"

    # else if it is a command, show the command how to view it
    else
      COMMAND_NAME="$(echo ${FILE_SHORT} | cut -d '/' -f 2)"
      echo_color "yellow" "Command: cheat ${COMMAND_NAME%.*}"
    fi

    # output line as bat one line no header
    if [[ "${DATA}" == \#* ]]; then
      # If the grep result starts with a #, then output the next line too
      NEXT_LINE="$(grep -A 1 "${DATA}" "${FILE}")"
      print_command "${LANGUAGE}" "${NEXT_LINE}"
    else
      print_command "${LANGUAGE}" "${DATA}"
    fi
  done
}

# cheat <BINARY> [online]
cheat_binary () {
  local BINARY="${1}"
  local ONLINE="${2}"

  local BINARY_FILE="${COMMANDS_DIR}/${BINARY}.sh"
  if [[ ! -f "${BINARY_FILE}" ]]; then
    if [[ "${ONLINE}" == "False" ]]; then
      echo_color "red_bold" "No custom entry for command '${BINARY}'. Showing online cheats now."
      ONLINE="True"
    fi
  else
    print_file "${BINARY_FILE}"
  fi

  if [[ "${ONLINE}" == "True" ]]; then
    echo
    echo_color "purple_bold" "All information found on http://cheat.sh:"
    echo
    curl "cheat.sh/${BINARY}"
  fi
}


# ------------------------------------------------------------------------------
# MAIN
# ------------------------------------------------------------------------------

echo

if [[ -z ${ACTION} ]]; then
  show_help
  exit
fi

case "${ACTION}" in
  "help"|"-h"|"--help")
    show_help
    exit
    ;;

  "list")
    TYPE="${2:-}"
    if [[ -z ${TYPE} ]]; then
      log "ERROR" "Action 'list' requires a second argument. Refer to the help message for more info."
    else
      case "${TYPE}" in
        "all")
          WHAT="${3}"
          if [[ "${WHAT}" == "snippets" ]]; then
            list_all_snippets
          else
            log "ERROR" "Action 'list all' requires a third argument. Refer to the help message for more info."
          fi
        ;;
        "sections")
          list_sections
        ;;
        *)
          SECTION="${TYPE}"
          WHAT="${3}"
          if [[ "${WHAT}" == "snippets" ]]; then
            list_snippets_for_section "${SECTION}"
          else
            log "ERROR" "Action 'list all' requires a third argument. Refer to the help message for more info."
          fi
      esac
    fi
    ;;

  "show")
    TYPE="${2}"
    if [[ -z ${3:-} ]]; then
      log "ERROR" "Action 'show' requires at least a second and third argument. Refer to the help message for more info."
    else
      case "${TYPE}" in
        "all")
          WHAT="${3}"
          if [[ "${WHAT}" == "snippets" ]]; then
            show_all_snippets
          else
            SECTION="${WHAT}"
            WHAT="${4:-}"
            if [[ -z ${WHAT} ]]; then
              log "ERROR" "Action 'show all <SECTION>' requires a fourth argument. Refer to the help message for more info."
            else
              show_all_snippets_for_section "${SECTION}"
            fi
          fi
        ;;
        *)
          SECTION="${TYPE}"
          WHAT="${3}"
          SNIPPET_NAME="${4:-}"
          if [[ -z ${SNIPPET_NAME} ]]; then
            if [[ -z ${WHAT} ]]; then
              log "ERROR" "Action 'show <SECTION>' requires a third and optionally fourth argument. Refer to the help message for more info."
            elif [[ "${WHAT}" != "snippet" ]]; then
              log "ERROR" "Unknown argument '${WHAT}' for action 'show <SECTION>. Refer to the help message for more info."
            else
              show_snippet_for_section "${SECTION}"
            fi
          else
            show_snippet "${SECTION}" "${SNIPPET_NAME}"
          fi
      esac
    fi
    ;;

  "grep")
      STRING="${2}"
      if [[ -z ${STRING} ]]; then
        log "ERROR" "Please provide a string to grep."
      fi
      grep_string "${@:2}"
    ;;

  *)
    BINARY="${ACTION}"
    ONLINE="${2:-}"
    if [[ -z ${ONLINE} ]]; then
      ONLINE="False"
    elif [[ "${ONLINE}" == "online" ]]; then
      ONLINE="True" 
    else
      log "ERROR" "Binary cheat has no option '${ONLINE}'. Only 'online' is a valid option or provide none."
    fi
    cheat_binary "${BINARY}" "${ONLINE}"
    ;;
esac

echo
exit 0

